<a href="https://colab.research.google.com/github/natashanuto/CEE2/blob/main/Exercicios.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício 1:
Crie um código que escreva "Olá, seu primeiro nome".


In [1]:
print("Olá, Natasha")

Olá, Natasha


## Exercício 2: Convertendo entre int e float

Crie três variáveis: uma do tipo `int`, uma do tipo `float` e uma do tipo `bool`. Exiba os valores de cada uma dessas variáveis e o tipo delas. Em seguida, converta as variáveis de acordo com as instruções abaixo:

* Converta o número inteiro para float e exiba o resultado.
* Converta o número decimal (float) para int e exiba o resultado.
* Converta o valor booleano para int e exiba o resultado.
* Converta o valor booleano para float e exiba o resultado.


In [4]:
x = int("1")
y = float("1.0")
w = bool(0)

print(x, type(x))
print(y, type(y))
print(w, type(w))

x = float(x)
print(x, type(x))

y = int(y)
print(y, type(y))

w = int(w)
print(w, type(w))

w = float(w)
print(w, type(w))

1 <class 'int'>
1.0 <class 'float'>
False <class 'bool'>
1.0 <class 'float'>
1 <class 'int'>
0 <class 'int'>
0.0 <class 'float'>


## Exercício 3: Operações básicas com int e float

Crie duas variáveis: uma contendo um número inteiro igual a 5 (`num1 = 5`) e outra contendo um número decimal float igual a 2.5 (`num2 = 2.5`). Em seguida, execute as seguintes operações e exiba o resultado:

* Adição  (`num1 + num2`)
* Subtração (`num1 - num2`)
* Multiplicação (`num1 * num2`)
* Divisão (`num1 / num2`)

Observe que a conversão para float é feita automaticamente.


In [6]:
num1 = int(5)
num2 = float(2.5)

a = num1 + num2
print(a)
s = num1 - num2
print(s)
m = num1 * num2
print(m)
d = num1 / num2
print(d)

7.5
2.5
12.5
2.0


## Exercício 4: Calculando a área de um círculo

Crie um programa que calcule a área de um círculo, dada a fórmula: $A = \pi * r^2$. Atribua um valor para o raio (como float) e mostre o resultado da área. Utilize π = 3.14159.

* O resultado deve ser apresentado como "A área do círculo é: {area}"

In [10]:
import math

r = float(input())
a = math.pi * r**2

print(f"A área do círculo é: {a}")

3
A área do círculo é: 28.274333882308138


## Exercício 5: Conversor de Temperatura

Crie um programa que converta uma temperatura de graus Celsius para Fahrenheit.

A fórmula de conversão é:
$$
Fahrenheit = Celsius \times \frac{9}{5} + 32
$$

Obs: para receber a temperatura em Celsius do usuário, utilize o comando:

 * `celsius = float(input("Digite a temperatura em Celsius: "))`

In [11]:
c = float(input())
f = c * (9/5) + 32

print(f)

2
35.6


## Exercício 6: Calculadora de IMC

Crie um programa que recebe calcula o Índice de Massa Corporal (IMC). Para isto você deve receber do usuário o peso e a altura.

A fórmula do IMC é dada por:
$$
IMC = peso / altura^2,
$$
em que peso é dado em kg e a altura em metros.

Obs: utilize os seguintes comandos para ser o peso e a altura:
* `peso = float(input("Digite o peso em quilogramas: "))`
* `altura = float(input("Digite a altura em metros: "))`

In [12]:
p = float(input())
a = float(input())

imc = p / (a)**2

print(imc)

1
2
0.25


## Exercício 7: Modificando uma lista

Dada a lista `frutas = ["maçã", "banana", "laranja", "uva"]`, faça o seguinte:

* Substitua a fruta "banana" por "abacaxi".
* Adicione a fruta "morango" ao final da lista.
* Exiba a lista resultante.
* Coloque a lista em ordem alfabética.
* Substitua a fruta "maçã" por "pera".
* Exiba a lista e verifique se ainda esta ordenada. Caso não esteja, então ordene e exiba novamente.

In [27]:
frutas = ["maçã", "banana", "laranja", "uva"]

print(frutas.index("banana"))

frutas[1] = "abacaxi"
print(frutas)

frutas.append("morango")
print(frutas)

frutas.sort()
print(frutas)

frutas.index("maçã")
frutas[2] = "pera"

print(frutas)
frutas.sort()
print(frutas)

1
['maçã', 'abacaxi', 'laranja', 'uva']
['maçã', 'abacaxi', 'laranja', 'uva', 'morango']
['abacaxi', 'laranja', 'maçã', 'morango', 'uva']
['abacaxi', 'laranja', 'pera', 'morango', 'uva']
['abacaxi', 'laranja', 'morango', 'pera', 'uva']


## Exercício 8: Trabalhando com tupla

Dada a tupla `dados = ("Maria", 28, "Engenheira", "São Paulo")`:
- Exiba o índice onde está o valor "Engenheira" na tupla.
- Faça o desempacotamento da tupla nas variáveis: nome, idade, profissao e cidade.
- Utilize f-string para formar e apresentar a seguinte frase: "Maria tem 28 anos, é Engenheira e mora em São Paulo."


In [30]:
dados = ("Maria", 28, "Engenheira", "São Paulo")

print(dados.index("Engenheira"))

nome, idade, profissao, cidade = dados
print(nome)
print(idade)
print(profissao)
print(cidade)

print(f"{nome} tem {idade} anos, é {profissao} e mora em {cidade}.")

2
Maria
28
Engenheira
São Paulo
Maria tem 28 anos, é Engenheira e mora em São Paulo.


## Exercício 9: Operações com `set`.

Crie um set chamado `frutas` contendo as frutas `"maçã", "banana", "laranja"` e `"uva"` e então:
* exiba o conteúdo;
* adicione a fruta "abacaxi" e exiba o resultado;
* remova o elemento "banana" e exiba o resultado;
* faça a união do set `frutas` com o set `vermelhas = {"morango", "cereja", "amora"}`, guarde em `frutas` e exiba o resultado;
* exiba a interseção do conjunto `frutas` com o conjunto `frutas2 = {"banana", "pera", "morango"}`.

In [33]:
frutas = {"maçâ", "banana", "laranja", "uva"}
print(frutas)

frutas.add("abacaxi")
print(frutas)

frutas.discard("banana")
print(frutas)

vermelhas = {"morango", "cereja", "amora"}
frutas = frutas.union(vermelhas)
print(frutas)

frutas2 = {"banana", "pera", "morango"}
print(frutas.intersection(frutas2))

{'laranja', 'uva', 'maçâ', 'banana'}
{'abacaxi', 'uva', 'laranja', 'maçâ', 'banana'}
{'abacaxi', 'uva', 'laranja', 'maçâ'}
{'laranja', 'maçâ', 'abacaxi', 'morango', 'cereja', 'uva', 'amora'}
{'morango'}


## Exercício 10: utilizando range

1. exiba o resultado do `range(0, 30, 2)`;
2. exiba todos os números pares entre 50 e 70;
3. exiba todos os números ímpares entre 50 e 70;
4. exiba todos os números que são multiplos de 5 entre 17 e 69.


In [37]:
for i in range(0, 30, 2):
  print(i)

for i in range(50, 71, 2):
  print(i)

for i in range(51, 70, 2):
  print(i)

for i in range(20, 69, 5):
  print(i)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
50
52
54
56
58
60
62
64
66
68
70
51
53
55
57
59
61
63
65
67
69
20
25
30
35
40
45
50
55
60
65


## Exercício 11: Crie um programa que pergunte o preço de um produto e verifique se ele deve aplicar algum desconto:

* Se o preço for maior que R$ 1000, aplique um desconto de 10%.
* Caso contrário, aplique um desconto de 5%.

Exiba o valor final do produto após o desconto.

In [44]:
p = float(input())

if p > 0:
  if p > 1000:
    p = p - (0.1 * p)
    print(p)
  else:
    p = p - (0.05 * p)
    print(p)
else:
  print("invalido")

-2
invalido


## Exercício 12: Escreva um programa que atribua menção para um aluno da UNB de acordo com o padrão da universidade. Inicialize perguntando a Nota Final e a Frequência do aluno. Classifique de acordo com os critérios:
- Frequência $ < $ 70\% : SR
- Frequência $\geq$ 70\% e $0 \leq NF < 3$: II
- Frequência $\geq$ 70\% e $3 \leq NF < 5$: MI
- Frequência $\geq$ 70\% e $5 \leq NF < 7$: MM
- Frequência $\geq$ 70\% e $7 \leq NF < 9$: MS
- Frequência $\geq$ 70\% e $9 \leq NF \leq 10$: SS


In [56]:
nf = float(input())
fq = float(input())


if fq >= 70 and 0 <= nf <= 10:
  if 0 <= nf < 3:
    print("ii")
  elif 3<= nf < 5:
    print("mi")
  elif 5<= nf < 7:
    print("mm")
  elif 7<= nf < 9:
    print("ms")
  else:
    print("ss")
elif 0 < fq < 70:
  print("sr")
else:
  print("invalido")


9
0
invalido


## Exercício 13: Soma dos primeiros 100 números

a) Use um laço `while` para calcular a soma dos primeiros 100 números inteiros (de 1 a 100).

b)  Use um laço `for` para calcular a soma dos primeiros 100 números inteiros (de 1 a 100).

In [59]:
i = 1
soma = 0

while i < 101:
  soma += i
  i += 1

print(soma)

soma2 = 0
for i in range(101):
  soma2 += i

print(soma2)

5050
5050


## Exercício 14: Números ímpares com `continue`

Use um laço `for` para exibir todos os números de 1 a 10, exceto os números ímpares (use o `continue`).

In [60]:
for i in range(1,11):
  if i % 2 != 0:
    continue
  else:
    print(i)

2
4
6
8
10


## Exercício 15: Sequência de Fibonacci

Use um laço `while` para calcular e exibir os primeiros 15 termos da sequência de Fibonacci.

A sequência de Fibonacci começa com 0 e 1, e os próximos números são a soma dos dois números anteriores.

Sequência: 0, 1, 1, 2, 3, 5, ...

In [64]:
i = 1
x = 0
y = 1
lista = [x, y]

while i < 16:
  soma = x + y
  lista.append(soma)
  x = y
  y = soma
  i += 1

print(lista)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]


## Exercício 16: Análise de Números

Crie uma função chamada `analisar_numeros` que recebe uma lista de números inteiros como parâmetro.

A função deve retornar dois objetos:

- Uma nova lista contendo apenas os números pares da lista original.

- Um dicionário com as seguintes informações:

  - "maior": o maior valor da lista

  - "menor": o menor valor da lista

  - "soma": a soma de todos os valores da lista

In [ ]:
def analisar_numeros(lista*):
  nova = list()
  for i in lista:
    if i % 2 == 0:
      nova.append(i)




## Exercício 17: Converter Celsius em Fahrenheit

Crie uma função chamada `celsius_para_fahrenheit` que recebe uma temperatura em graus Celsius e retorna a temperatura equivalente em Fahrenheit. A fórmula de conversão é: $ 𝐹 = 𝐶 \times 9/5 + 32$.

- Faça um print do resultado.

- Documente a função.

## Exercício 18:

Para a lista abaixo, escreva um programa que peça ao usuário um índice e então apresente o elemento da lista na posição correspondente. Trate os possíveis erros:
* O valor digitado não for um número (ValueError).
* O índice estiver fora do intervalo da lista (IndexError).

```python
lista = ["maçã", "banana", "laranja", "uva", "melancia"]
```


## Exercício 19:

Crie uma função chamada `extrair_dominio` que recebe um endereço de email como parâmetro e retorna apenas o domínio (parte após o @). Use `split()` para dividir o email e extrair o domínio.

Exemplo:
```python
extrair_dominio("usuario@dominio.com")  # Saída: "dominio.com"
```


In [67]:
def extrair_dominio (email):
  dominio = email.split("@")
  return print(dominio[1])

extrair_dominio("usuario@dominio.com")

dominio.com


## Exercício 20:

Construa um código que altera um número de telefone no formato "61997351520" para o formato "(61) 99735-1520".

Exemplo:
```python
altera_telefone(61997351520)  # Saída: "(61) 99735-1520"
```

In [74]:
def altera_telefone(tel):
  tel = str(tel)
  ddd = tel[0:2]
  x = tel[2:7]
  y = tel[7:]
  return print(f"({ddd}) {x}-{y}")

altera_telefone(61997351520)

(61) 99735-1520


## Exercício 21:

Crie uma expressão regular que valide CEPs no formato XXXXX-XXX, onde X é um dígito. Escreva uma função validar_cep que recebe uma string e retorna True se o CEP for válido, caso contrário, False.

```python
validar_cep("12345-678")  # True
validar_cep("1234-678")   # False
```

In [76]:
import re

def validar_cep(cep):
  padrao = r"\d{5}-\d{3}"
  if re.fullmatch(padrao, cep):
    print("true")
  else:
    print("false")

validar_cep("12345-678")
validar_cep("1234-678")

true
false


## Exercício 22:

Crie uma função que verifica se placas de carro estão no formato antigo brasileiro (AAA-1234), onde A é uma letra maiúscula e 1-4 são números.

Exemplo:

```python
verifica_placa("PHL-2526") # True
verifica_placa("AAB9E81")  # False
```

In [78]:
def verifica_placa(placa):
  padrao = "[A-Z]{3}-\d{4}"
  if re.fullmatch(padrao, placa):
    print("true")
  else:
    print("false")

verifica_placa("PHL-2526") # True
verifica_placa("AAB9E81")

true
false


## Exercício 23

a) Crie um array de zeros com forma 3x3.

b) Crie um array com números de 1 a 20, com passo de 3.

In [83]:
import numpy as np

x = np.zeros((3,3))
print(x)

y = np.arange(1,20,3)
print(y)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[ 1  4  7 10 13 16 19]


## Exercício 24

* Crie um array com os valores `[10, 20, 30, 40, 50]`.
* Subtraia `5` de cada elemento e, em seguida, eleve ao quadrado cada valor.
* Apresente o vetor com a soma das colunas.

In [85]:
x = np.array([10, 20, 30, 40, 50])
x -= 5
print(x)
x **= 2
print(x)

print(x.sum(axis=0))

[ 5 15 25 35 45]
[  25  225  625 1225 2025]
4125


## Exercício 25

* Crie um array 3x3 com valores de 1 a 9.
* Extraia a segunda linha.
* Extraia o último elemento da primeira linha.

In [89]:
x = np.arange(1,10).reshape(3,3)
print(x)

print(x[1, :])
print(x[0,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
3


## Exercício 26

1. Crie dois arrays 1D, `a` e `b`, com valores de 1 a 5 e de 6 a 10, respectivamente.
1. Empilhe `a` e `b` verticalmente para formar um array 2D.
1. Em seguida, empilhe `a` e `b` horizontalmente para formar um array 1x10.

Dica: Use np.vstack() para empilhamento vertical e np.hstack() para empilhamento horizontal.

In [92]:
a = np.arange(1, 6)
b = np.arange(6, 11)

print(a)
print(b)
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[1 2 3 4 5]
[ 6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


## Exercício 27

1. Crie uma matriz A de tamanho 4x3 de zeros.
1. Faça `B=A` e `C=A.copy()`.
1. Verifique se `B` e `C` são os mesmos objetos utilizando `is`.
1. Mostre os id's de `A`, `B` e `C`.
1. Altere um elemento de `A` e veja o que acontece com `B` e com `C`.

In [98]:
a = np.zeros((4,3))
b = a
c = a.copy()

print(b is c)
print(id(a))
print(id(b))
print(id(c))

a[0,0] = 2

print(a)
print(b)
print(c)

False
136780663004816
136780663004816
136780663005488
[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Exercício 28:

Crie um vetor do tipo `Series` com:
* as seguintes datas como indices: "2023-01-01", "2023-03-15", "2023-07-20", "2023-12-25".
  * dica: utilize `pd.to_datetime(["2023-01-01", "2023-03-15", "2023-07-20", "2023-12-25"])`
* os seguintes valores:  100, 200, 300, 400

## Exercício 29

Crie um `DataFrame` com 3 colunas chamadas `["Número", "Quadrado", "Cubo"]`. Preencha com os números de 1 a 10 na coluna `Número`, e nas colunas `Quadrado` e `Cubo`, insira os valores correspondentes ao quadrado e ao cubo de cada número.


## Exercício 30

Considere o seguinte `DataFrame`:
```python
df = pd.DataFrame({
    "Nome": ["Ana", "Bruno", "Clara", "Diego"],
    "Idade": [23, 35, 29, 40],
    "Cidade": ["São Paulo", "Rio de Janeiro", "Belo Horizonte", "Curitiba"]
})
```
Então:

1. Selecione apenas a coluna `Idade`.
1. Selecione as colunas ["Nome", "Cidade"].
1. Filtre apenas as linhas onde a idade seja maior que 30.

## Exercício 31

Considere o seguinte `DataFrame`:
```python
df = pd.DataFrame({
    "População (milhões)": [211, 144, 331, 67, 83],
    "PIB (trilhões USD)": [1.84, 1.48, 22.68, 2.83, 4.22],
    "Continente": ["América", "Asia", "América", "Europa", "Europa"]
    },
    index=["Brasil", "Rússia", "Estados Unidos", "França", "Alemanha"])
```
Então:

1. Selecione as linhas correspondentes a "Brasil" e "Alemanha".
1. Use `.loc` para selecionar a população e o PIB dos "Estados Unidos".
1. Use `.iloc` para selecionar os dados dos dois primeiros países.
1. Use `.isin` para todos os países que estão na América ou na Asia.

## Exercício 32


Considere o seguinte `DataFrame`:
```python
dados = {
    "Produto": ["Notebook", "Celular", "Tablet", "Fone de Ouvido", "Monitor", "Mouse"],
    "Preço": [2500, 1500, np.nan, 200, 800, 100],
    "Estoque": [10, 5, 2, 50, np.nan, 150],
    "Categoria": ["Eletrônicos", "Eletrônicos", "Eletrônicos", "Acessórios", "Periféricos", "Periféricos"],
    "Avaliação": [4.5, np.nan, 3.8, 4.2, 3.9, np.nan]
}

df = pd.DataFrame(dados)
```
Então:

1. Atualize o preço do produto "Tablet" para 1800.
1. Reduza em 20% o preço de todos os produtos da categoria "Eletrônicos".
1. Mostre a planilha excluindo as linhas com valores faltantes.
1. Preencha os valores faltantes na coluna Estoque com 0.

## Exercício 33

Considere o seguinte `DataFrame`:
```python
dados = {
    "Região": ["Norte", "Norte", "Sul", "Sul", "Leste", "Leste"],
    "Produto": ["Maçã", "Banana", "Maçã", "Banana", "Maçã", "Banana"],
    "Vendas": [120, 200, 150, 300, 250, 180],
    "Lucro": [30, 50, 25, 70, 60, 40],
    "Desconto (%)": [5, 10, 0, 15, 5, 10],
}
df = pd.DataFrame(dados)
```
Então:

1. Use `DataFrame.agg()` para calcular, para cada coluna numérica do DataFrame:
  * A soma;
  * A média;
  * O valor máximo;

1. Use `DataFrame.transform()` para criar uma nova coluna chamada *Vendas Normalizadas*, que:
  * Subtraia a média das vendas de cada valor.
  * Divida pelo desvio padrão das vendas.
  
  Dica: Aplique a normalização (fórmula: $z = (x - média) / std$) diretamente sobre a coluna *Vendas*.


## Exercício 34

Considere o seguinte `DataFrame`:
```python
dados = {
    "Cliente": ["Ana", "bruno", "Carlos", "Diana", "Eduarda", np.nan, "fábio", "Gabriela"],
    "Produto": ["Notebook", "Smartphone", "Notebook", "Tablet", "Notebook", "Smartphone", np.nan, "Tablet"],
    "Valor": [3000, 2000, 3000, 1500, 3000, 2000, 1500, 1500],
    "Data": ["2023-01-15", "2023-01-16", np.nan, "2023-02-10", "2023-02-10", "2023-01-16", "2023-02-15", "2023-02-16"],
}
df = pd.DataFrame(dados)
```
Então:

1. Qual é o número de valores não nulos em cada coluna do DataFrame?
  
  Dica: Utilize o método `count()`.

1. Qual produto foi vendido mais vezes?
  
  Dica: Utilize o método `value_counts()` para listar a quantidade de prudutos vendidos e `.idxmax()` para mostrar qual o produto mais vendito.
  
1. Passe a primeira letra do nome de cada cliente para maiúscula. Dica: Utilize o método `str.title()`.

1. Inclua o seguinte dados no final do `df`:
```python
df2 = pd.DataFrame({
    "Cliente": ["Jose", "Paula"],
    "Produto": ["Tablet", "Notebook"],
    "Valor": [1500, 4000],
    "Data": ["2023-03-01", "2023-03-02"],
})
```


## Exercício 35


1. Para o código abaixo use a função `merge()` para combinar os dois DataFrames com base na coluna `Produto`.
  * E depois `how="outer"` (união de todos os dados).  
  * E depois `how="inner"` (interseção entre os DataFrames).

2. Para a ultima junção, faça um agrupamento pela coluna `Produto` e então selecione as colunas `Quantidade` e `Preço` e some elas.

```python
import pandas as pd

# DataFrame de produtos vendidos
vendas = pd.DataFrame({
    "Cliente": ["Ana", "Bruno", "Carlos", "Diana", "Eduarda", "Fábio", "Gabriela"],
    "Produto": ["Notebook", "Smartphone", "Notebook", "Tablet", "Notebook", "Mouse", "Smartphone"],
    "Data": ["2023-01-15", "2023-01-16", "2023-01-16", "2023-02-10", "2023-02-10", "2023-02-15", "2023-02-16"],
    "Quantidade": [1, 2, 1, 1, 3, 2, 1],
})

# DataFrame com os preços dos produtos
precos = pd.DataFrame({
    "Produto": ["Notebook", "Smartphone", "Tablet"],
    "Preço": [3000, 2000, 1500],
})

print("DataFrame de vendas:")
print(vendas)

print("\nDataFrame de preços:")
print(precos)
```

In [103]:
import pandas as pd

# DataFrame de produtos vendidos
vendas = pd.DataFrame({
    "Cliente": ["Ana", "Bruno", "Carlos", "Diana", "Eduarda", "Fábio", "Gabriela"],
    "Produto": ["Notebook", "Smartphone", "Notebook", "Tablet", "Notebook", "Mouse", "Smartphone"],
    "Data": ["2023-01-15", "2023-01-16", "2023-01-16", "2023-02-10", "2023-02-10", "2023-02-15", "2023-02-16"],
    "Quantidade": [1, 2, 1, 1, 3, 2, 1],
})

# DataFrame com os preços dos produtos
precos = pd.DataFrame({
    "Produto": ["Notebook", "Smartphone", "Tablet"],
    "Preço": [3000, 2000, 1500],
})

print("DataFrame de vendas:")
print(vendas)

print("\nDataFrame de preços:")
print(precos)

print(pd.merge(vendas, precos, how = "outer"))
print(pd.merge(vendas, precos, how = "inner"))

x = pd.merge(vendas, precos, how = "inner")
print(x.groupby("Produto")[["Quantidade", "Preço"]].sum())

DataFrame de vendas:
    Cliente     Produto        Data  Quantidade
0       Ana    Notebook  2023-01-15           1
1     Bruno  Smartphone  2023-01-16           2
2    Carlos    Notebook  2023-01-16           1
3     Diana      Tablet  2023-02-10           1
4   Eduarda    Notebook  2023-02-10           3
5     Fábio       Mouse  2023-02-15           2
6  Gabriela  Smartphone  2023-02-16           1

DataFrame de preços:
      Produto  Preço
0    Notebook   3000
1  Smartphone   2000
2      Tablet   1500
    Cliente     Produto        Data  Quantidade   Preço
0     Fábio       Mouse  2023-02-15           2     NaN
1       Ana    Notebook  2023-01-15           1  3000.0
2    Carlos    Notebook  2023-01-16           1  3000.0
3   Eduarda    Notebook  2023-02-10           3  3000.0
4     Bruno  Smartphone  2023-01-16           2  2000.0
5  Gabriela  Smartphone  2023-02-16           1  2000.0
6     Diana      Tablet  2023-02-10           1  1500.0
    Cliente     Produto        Data  Quan

## Exercício 36

Considere o seguinte conjunto de dados:
```python
import pandas as pd
import numpy as np

# DataFrame para os exercícios
dados = {
    "Produto": ["Notebook", "Notebook", "Smartphone", "Smartphone", "Tablet", "Tablet"],
    "Região": ["Norte", "Sul", "Norte", "Sul", "Norte", "Sul"],
    "Ano": [2023, 2023, 2024, 2024, 2023, 2024],
    "Vendas": [5000, 4500, 3000, 3500, 2000, 2500],
    "Lucro": [1000, 900, 800, 850, 300, 400],
}

df = pd.DataFrame(dados)
print(df)
```

Então:

1. Aplique `stack()` no DataFrame original e observe como ele transforma as colunas em um índice.

  Pergunta: Qual a principal diferença entre o DataFrame antes e depois de usar `stack()`?

2. A partir do resultado de `stack()`, use `unstack()` para reorganizar os dados. Experimente utilizar os níveis de índice (0, 1 ou nomeados).

3. Crie uma tabela dinâmica que mostre o lucro médio (Lucro) por "Produto" e "Região". Use `aggfunc="mean"`.

  Pergunta: Como a função de agregação afeta os dados?

4. Adicione margens (totais) à tabela dinâmica do exercício anterior, usando o parâmetro `margins=True`.   

In [105]:
import pandas as pd
import numpy as np

# DataFrame para os exercícios
dados = {
    "Produto": ["Notebook", "Notebook", "Smartphone", "Smartphone", "Tablet", "Tablet"],
    "Região": ["Norte", "Sul", "Norte", "Sul", "Norte", "Sul"],
    "Ano": [2023, 2023, 2024, 2024, 2023, 2024],
    "Vendas": [5000, 4500, 3000, 3500, 2000, 2500],
    "Lucro": [1000, 900, 800, 850, 300, 400],
}

df = pd.DataFrame(dados)
print(df)

print(df.stack())
print(df.unstack())
print(df.unstack(0))
print(df.unstack(1))

      Produto Região   Ano  Vendas  Lucro
0    Notebook  Norte  2023    5000   1000
1    Notebook    Sul  2023    4500    900
2  Smartphone  Norte  2024    3000    800
3  Smartphone    Sul  2024    3500    850
4      Tablet  Norte  2023    2000    300
5      Tablet    Sul  2024    2500    400
0  Produto      Notebook
   Região          Norte
   Ano              2023
   Vendas           5000
   Lucro            1000
1  Produto      Notebook
   Região            Sul
   Ano              2023
   Vendas           4500
   Lucro             900
2  Produto    Smartphone
   Região          Norte
   Ano              2024
   Vendas           3000
   Lucro             800
3  Produto    Smartphone
   Região            Sul
   Ano              2024
   Vendas           3500
   Lucro             850
4  Produto        Tablet
   Região          Norte
   Ano              2023
   Vendas           2000
   Lucro             300
5  Produto        Tablet
   Região            Sul
   Ano              2024
   Ven

## Exercício 37

Considere o seguinte código:

```python
import pandas as pd
import numpy as np

# Série temporal diária para janeiro de 2023
dias = pd.date_range(start="2023-01-01", end="2023-01-31", freq="D")
serie = pd.Series(np.random.randint(10, 100, len(dias_janeiro)), index=dias)
print("Série Temporal:\n", serie)
```

Então para o objeto `serie`:

1. Construa uma série semanal tomando os valores máximos de cada semana.

2. Construa uma série semanal tomando os valores médios de cada semana.

3. Inclua o fuso horário "America/Sao_Paulo".

4. Apresente o gráfico das duas séries temporais.

## Exercício 38

Considere o seguinte código que construi um dataframe representando vendas de um loja de eletrônicos:

```python
import pandas as pd
import numpy as np

# Criando um DataFrame de exemplo
dados = {
    "Produto": ["Notebook", "Smartphone", "Tablet", "Notebook", "Smartphone", "Tablet", "Notebook", "Smartphone", "Tablet", "Notebook"],
    "Loja": ["Loja A", "Loja B", "Loja C", "Loja A", "Loja B", "Loja C", "Loja A", "Loja B", "Loja C", "Loja A"],
    "Vendas": [1500, 2000, 1000, 1800, 2200, 1200, 1700, 2100, 1300, 1600],
    "Ano": [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023],
    "Categoria": ["Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos", "Eletrônicos"],
}

df = pd.DataFrame(dados)

print("Conjunto de Dados de Vendas:")
print(df)

```

Então para o objeto `serie`:

1. Converta as colunas "Loja" e "Produto" para categóricas.

2. Faça a coluna "Produto" ter a seguinte ordem: "Tablet", "Smartphone", "Notebook".

3. Calcule a quantidade de ocorrências de cada nível da coluna "Loja" usando `value_counts()`.

4. Crie uma nova coluna categórica ordinal chamada `Categoria_Vendas`, onde será categorizado para "Alto", "Médio" ou "Baixo", com base nos seguintes critérios:
  * "Alto": Vendas > 2000
  * "Médio": 1500 <= Vendas <= 2000
  * "Baixo": Vendas < 1500.

5. Transforme em dummies as variáveis `Produto` e  `Categoria_Vendas`.    